### PR TITLE
Fix for later forge versions

### PR DESCRIPTION
**Pull request by OwlyCode**
Here is a quick fix for the lastest forge version.

It's dirty but will allow it to quickly work. If you want I can help with further improvement more in the "state of the art".

### CODE REVIEW

**Comment by ghost** [comment]
this patch does not resolve SMP connection problem

https://github.com/MinecraftForge/MinecraftForge/issues/1973

Lex said on IRC:
(16:54:18) Lex__: Hunterz, thats not forge, something on their end is fucking over the fluid registry.
(16:59:43) Lex|Hotel: Somehow they have multiple ids going to the same fluid name, but not instance.

**Comment by OwlyCode** [comment]
I did not encounter this bug, can you provide me a way to reproduce ?

**Comment by ghost** [comment]
run server with crowthcraft, connect to it - client crashes

**Comment by OwlyCode** [comment]
I did not encounter that problem on my multi server. I shared my jar with my friends and there is no problem (using Forge forge-1.7.10-10.13.4.1448 and adding the mod to Feed the Best Horizon : Daybreak)

**Comment by spannerman79** [comment]
@hunter688 what forge version?  As i myself did what @OwlyCode have done and there is no issue, server side or client side.  And I was using recommended forge version of 1448

**Comment by ghost** [comment]
1470, 1481

**Comment by spannerman79** [comment]
Try with recommended forge version 1448.
Those versions are considered bleeding edge/bug prone

**Comment by ghost** [comment]
Looks like forge bug: https://github.com/MinecraftForge/MinecraftForge/issues/1973

With old forge looks like it works.

**Comment by Techokami** [comment]
I can confirm this works flawlessly with Forge 10.13.4.1481, have been brewing booze on a SMP server without any issues.

**Comment by matt2887** [comment]
How do I use these files to fix growthcraft to work with Forge 10.13.4.1481. Do I simply add them to my mod list?

**Comment by Alatyami** [comment]
Yes just switch them out.

**Comment by matt2887** [comment]
Ok so I took a look at the files, first question is where should I put the resources folder that's in the src folder? same thing with the different folders in the src\java\growthcraft folder? Or should this whole zip file itself go in the mods folder?

Sorry if I'm asking derp questions. Just wanna make sure I do this right lol.

**Comment by YaoiSenpai** [comment]
So I know I'm really late on this but I also had this mod crash with forge 1614 when I clicked on the barrel. The files you posted  I can't download them to see if they will fix it and if I did I have no idea where to put them. So I'm not sure if people are still experiencing this or if anyone is going to work on a fix. In case I don't respond I hope somebody updates me at my email yaoixsenpai@gmail.com

**Comment by OwlyCode** [comment]
Closed as https://github.com/GrowthcraftCE/Growthcraft-1.7 pursued the job.

**Pull request closed without merging**
